# Generated by Django 5.1.2 on 2024-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0002_bookitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="BookItem",
        ),
    ]
